<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run()
    {
        Product::insert([
            [
                'name' => 'Air Blade 250',
                'description' => 'Honda Air Blade 250 mới, thiết kế thể thao',
                'image' => 'products/airblade 250.png',
                'price' => 42000000,
                'stock' => 10,
                'status' => 'available',
                'brand_id' => 1,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Angela 50',
                'description' => 'SYM Angela 50, xe số nhỏ gọn',
                'image' => 'products/angela 50.png',
                'price' => 17000000,
                'stock' => 8,
                'status' => 'available',
                'brand_id' => 4,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CBR150R Black',
                'description' => 'Honda CBR150R màu đen, xe côn tay thể thao',
                'image' => 'products/cbr150r black.png',
                'price' => 65000000,
                'stock' => 5,
                'status' => 'available',
                'brand_id' => 1,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Future',
                'description' => 'Honda Future, xe số bền bỉ',
                'image' => 'products/future.png',
                'price' => 31000000,
                'stock' => 12,
                'status' => 'available',
                'brand_id' => 1,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Galaxy 50',
                'description' => 'SYM Galaxy 50, xe số tiết kiệm',
                'image' => 'products/galaxy 50.png',
                'price' => 16000000,
                'stock' => 7,
                'status' => 'available',
                'brand_id' => 4,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GR200R Đen',
                'description' => 'GPX GR200R màu đen, mô tô thể thao',
                'image' => 'products/gr200r-den.png',
                'price' => 69000000,
                'stock' => 3,
                'status' => 'available',
                'brand_id' => 6,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Legend 150 FI',
                'description' => 'GPX Legend 150 FI, mô tô cổ điển',
                'image' => 'products/legend 150 fi.png',
                'price' => 55000000,
                'stock' => 4,
                'status' => 'available',
                'brand_id' => 6,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MT-15',
                'description' => 'Yamaha MT-15, xe côn tay thể thao',
                'image' => 'products/mt-15.png',
                'price' => 78000000,
                'stock' => 6,
                'status' => 'available',
                'brand_id' => 2,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MTS V4 R',
                'description' => 'Ducati MTS V4 R, mô tô phân khối lớn',
                'image' => 'products/MTS-V4-R-01-Book-testride_630x390-v05.png',
                'price' => 650000000,
                'stock' => 1,
                'status' => 'available',
                'brand_id' => 5,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Naga 150',
                'description' => 'SYM Naga 150, xe số mạnh mẽ',
                'image' => 'products/naga 150.png',
                'price' => 25000000,
                'stock' => 5,
                'status' => 'available',
                'brand_id' => 4,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PV2 Red',
                'description' => 'Ducati PV2 Red, mô tô phân khối lớn',
                'image' => 'products/PV2-Rd-MY22-Model-Preview-1050x650-v06.png',
                'price' => 720000000,
                'stock' => 1,
                'status' => 'available',
                'brand_id' => 5,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Satria F150',
                'description' => 'Suzuki Satria F150, xe côn tay thể thao',
                'image' => 'products/satria f150.png',
                'price' => 54000000,
                'stock' => 6,
                'status' => 'available',
                'brand_id' => 3,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shark 50',
                'description' => 'SYM Shark 50, xe ga nhỏ gọn',
                'image' => 'products/shark 50.png',
                'price' => 19000000,
                'stock' => 7,
                'status' => 'available',
                'brand_id' => 4,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'V-Strom 250SX Yellow',
                'description' => 'Suzuki V-Strom 250SX màu vàng',
                'image' => 'products/v-strom 250sx yellow.png',
                'price' => 105000000,
                'stock' => 2,
                'status' => 'available',
                'brand_id' => 3,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vario 125',
                'description' => 'Honda Vario 125, xe ga thể thao',
                'image' => 'products/vario 125.png',
                'price' => 34000000,
                'stock' => 9,
                'status' => 'available',
                'brand_id' => 1,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wave Alpha',
                'description' => 'Honda Wave Alpha, xe số phổ thông',
                'image' => 'products/wave alpha.png',
                'price' => 18000000,
                'stock' => 15,
                'status' => 'available',
                'brand_id' => 1,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Winner R',
                'description' => 'Honda Winner R, xe côn tay thể thao',
                'image' => 'products/winner r.png',
                'price' => 48000000,
                'stock' => 8,
                'status' => 'available',
                'brand_id' => 1,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yamaha Janus',
                'description' => 'Yamaha Janus, xe ga nhỏ gọn',
                'image' => 'products/xeSoYamahaJanus18_2b26874a3c425b00bd8ac80ca030ea5d.jpg',
                'price' => 28500000,
                'stock' => 20,
                'status' => 'available',
                'brand_id' => 2,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yamaha Lexi 155',
                'description' => 'Yamaha Lexi 155, xe ga tiêu chuẩn',
                'image' => 'products/yamaha-lexi-155-2024-tieu-chuan-2469618-0.png',
                'price' => 32000000,
                'stock' => 10,
                'status' => 'available',
                'brand_id' => 2,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YZF-R15 Monster',
                'description' => 'Yamaha YZF-R15 Monster, xe côn tay thể thao',
                'image' => 'products/yzf-r15 monster.png',
                'price' => 79000000,
                'stock' => 4,
                'status' => 'available',
                'brand_id' => 2,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
